name: sentence-clustering
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - abseil-cpp
  - aiohttp
  - aiosignal
  - archspec
  - arrow-cpp
  - asttokens
  - async-timeout
  - attrs
  - aws-c-common
  - aws-c-event-stream
  - aws-checksums
  - aws-sdk-cpp
  - backports
  - backports.functools_lru_cache
  - blas
  - boltons
  - boost-cpp
  - bottleneck
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - comm
  - conda
  - conda-libmamba-solver
  - conda-package-handling
  - conda-package-streaming
  - contourpy
  - cryptography
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-runtime
  - cycler
  - cyrus-sasl
  - datasets
  - dbus
  - debugpy
  - decorator
  - dill
  - et_xmlfile
  - exceptiongroup
  - executing
  - expat
  - ffmpeg
  - filelock
  - fmt
  - fontconfig
  - fonttools
  - freetype
  - frozenlist
  - fsspec
  - gflags
  - giflib
  - glib
  - glog
  - gmp
  - gmpy2
  - gnutls
  - grpc-cpp
  - gst-plugins-base
  - gstreamer
  - huggingface_hub
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonpatch
  - jsonpointer
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libarchive
  - libboost
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcublas
  - libcufft
  - libcufile
  - libcups
  - libcurand
  - libcurl
  - libcusolver
  - libcusparse
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libgomp
  - libiconv
  - libidn2
  - libjpeg-turbo
  - libllvm14
  - libmamba
  - libmambapy
  - libnghttp2
  - libnpp
  - libnvjpeg
  - libpng
  - libpq
  - libprotobuf
  - libsodium
  - libsolv
  - libssh2
  - libstdcxx-ng
  - libtasn1
  - libthrift
  - libtiff
  - libunistring
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzlib
  - llvm-openmp
  - llvmlite
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  - multidict
  - multiprocess
  - munkres
  - mysql
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - nltk
  - numba
  - numexpr
  - numpy
  - numpy-base
  - openh264
  - openjpeg
  - openpyxl
  - openssl
  - orc
  - packaging
  - pandas
  - parso
  - pcre
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - pluggy
  - ply
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pyarrow
  - pybind11-abi
  - pycosat
  - pycparser
  - pygments
  - pynndescent
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt5-sip
  - pysocks
  - python
  - python-dateutil
  - python-tzdata
  - python-xxhash
  - python_abi
  - pytorch
  - pytorch-cuda
  - pytorch-mutex
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - re2
  - readline
  - regex
  - reproc
  - reproc-cpp
  - requests
  - responses
  - ruamel.yaml
  - sacremoses
  - safetensors
  - scikit-learn
  - scipy
  - seaborn
  - sentence-transformers
  - sentencepiece
  - setuptools
  - sip
  - six
  - snappy
  - sqlite
  - stack_data
  - sympy
  - tbb
  - threadpoolctl
  - tk
  - tokenizers
  - torchaudio
  - torchtriton
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - transformers
  - truststore
  - typing-extensions
  - typing_extensions
  - tzdata
  - umap-learn
  - urllib3
  - utf8proc
  - wcwidth
  - wheel
  - xxhash
  - xz
  - yaml
  - yaml-cpp
  - yarl
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd
